_wandb:
    value:
        cli_version: 0.19.8
        m:
            - "1": conf_table.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": examples.ncols
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": valid/loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": conf_table.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": conf_table._latest_artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": conf_table.ncols
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": examples._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/acc_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": valid/recall_macro
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": conf_table.nrows
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": conf_table._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": examples.artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": valid/loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": valid/recall_micro
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": valid/acc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": valid/precision_macro
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": valid/precision_micro
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": conf_table.artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": conf_table.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": examples.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": examples.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": valid/f1
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/acc_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": examples._latest_artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": global_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": examples.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": examples.nrows
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 50
                - 51
                - 53
                - 55
                - 103
                - 105
            "2":
                - 1
                - 5
                - 9
                - 11
                - 49
                - 50
                - 51
                - 53
                - 55
                - 103
                - 105
            "3":
                - 2
                - 7
                - 23
                - 55
                - 66
            "4": 3.11.5
            "5": 0.19.8
            "6": 4.32.1
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
        visualize:
            conf:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: conf_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
lr:
    value: 0.01
model_name:
    value: google/bert_uncased_L-2_H-128_A-2
